import { StrictMode, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, AlertTriangle, ArrowUpRight, Bell, Box, Building2, CheckCircle2, CircleDot, CreditCard, MapPin, MapPinned, Package, Plus, Search, Store, Truck, Users, Warehouse, X } from 'lucide-react'
import './styles.css'

type OrderStatus = 'CREATED' | 'PAYMENT_PENDING' | 'INVENTORY_RESERVED' | 'PREPARING' | 'ASSIGNED' | 'IN_TRANSIT' | 'DELIVERED' | 'CANCELLED'
type Order = { id: number; customerName: string; deliveryAddress: string; total: number; status: OrderStatus; createdAt: string }
type Dashboard = { totalOrders: number; inTransit: number; delivered: number; cancelled: number }

const API = import.meta.env.VITE_API_URL ?? '/api'
// Es publico en la interfaz porque el diseno visual se preparo en Figma para que el equipo entienda el flujo del frontend.
const labels: Record<OrderStatus, string> = { CREATED: 'Creado', PAYMENT_PENDING: 'Pago pendiente', INVENTORY_RESERVED: 'Inventario reservado', PREPARING: 'En preparación', ASSIGNED: 'Asignado', IN_TRANSIT: 'En ruta', DELIVERED: 'Entregado', CANCELLED: 'Cancelado' }

function App() {
  const [orders, setOrders] = useState<Order[]>([])
  const [dashboard, setDashboard] = useState<Dashboard>({ totalOrders: 0, inTransit: 0, delivered: 0, cancelled: 0 })
  const [search, setSearch] = useState('')
  const [showForm, setShowForm] = useState(false)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  async function loadData() {
    try {
      const [ordersResponse, dashboardResponse] = await Promise.all([fetch(`${API}/orders`), fetch(`${API}/dashboard`)]); if (!ordersResponse.ok || !dashboardResponse.ok) throw new Error('API no disponible')
      setOrders(await ordersResponse.json()); setDashboard(await dashboardResponse.json()); setError('')
    } catch { setError('Conecta el backend y PostgreSQL para ver datos en vivo.') } finally { setLoading(false) }
  }
  useEffect(() => { loadData() }, [])

  async function updateStatus(id: number, status: OrderStatus) { await fetch(`${API}/orders/${id}/status?status=${status}`, { method: 'PATCH' }); loadData() }
  const filteredOrders = orders.filter(order => `${order.id} ${order.customerName} ${order.deliveryAddress}`.toLowerCase().includes(search.toLowerCase()))

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark"><Activity size={19} /></span><span>LAstrack<span>.ITM</span></span></div><div className="workspace-label">PLATAFORMA LOGÍSTICA</div><nav><a className="active"><Box size={17} />Resumen <span className="nav-count">{dashboard.totalOrders}</span></a><a><Package size={17} />Pedidos</a><a><Users size={17} />Clientes</a><a><Box size={17} />Inventario</a><a><Building2 size={17} />Almacenes</a><a><Truck size={17} />Entregas</a><a><MapPinned size={17} />Rutas y tracking</a><a><AlertTriangle size={17} />Incidencias</a><a><CreditCard size={17} />Pagos</a><a><Store size={17} />Canales de venta</a></nav><div className="sidebar-bottom"><div className="status-dot"><span /> Sistemas operativos</div><div className="user"><div className="avatar">JD</div><div><strong>Julián Díaz</strong><small>Administrador</small></div><ArrowUpRight size={15} /></div></div></aside>
    <main className="main"><header><div><p className="eyebrow">CENTRO DE OPERACIONES LOGÍSTICAS</p><h1>LAstrack.ITM</h1><p className="subhead">Gestión de pedidos y entregas de última milla.</p></div><div className="header-actions"><button className="icon-button" title="Notificaciones"><Bell size={18} /><i /></button><button className="primary-button" onClick={() => setShowForm(true)}><Plus size={17} /> Nuevo pedido</button></div></header>
      {error && <div className="connection-alert"><CircleDot size={17} />{error}</div>}
      <section className="metrics"><Metric icon={<Package />} label="Pedidos totales" value={dashboard.totalOrders} detail="+12% vs. ayer" positive /><Metric icon={<Truck />} label="En ruta" value={dashboard.inTransit} detail="Seguimiento activo" /><Metric icon={<CheckCircle2 />} label="Entregados" value={dashboard.delivered} detail="Últimas 24 horas" positive /><Metric icon={<CircleDot />} label="Incidencias" value={dashboard.cancelled} detail="Requieren atención" warning /></section>
      <section className="content-grid"><div className="orders-panel"><div className="panel-heading"><div><p className="eyebrow">OPERACIÓN</p><h2>Pedidos recientes</h2></div><div className="tools"><label className="search"><Search size={16} /><input placeholder="Buscar pedido o cliente" value={search} onChange={event => setSearch(event.target.value)} /></label><button className="text-button">Ver todos <ArrowUpRight size={15} /></button></div></div>{loading ? <div className="empty">Cargando operación...</div> : <div className="table-wrap"><table><thead><tr><th>PEDIDO</th><th>CLIENTE</th><th>ESTADO</th><th>TOTAL</th><th>UBICACIÓN</th><th /></tr></thead><tbody>{filteredOrders.map(order => <tr key={order.id}><td><strong className="order-id">#{String(order.id).padStart(5, '0')}</strong><small>{new Date(order.createdAt).toLocaleDateString('es-CO')}</small></td><td><strong>{order.customerName}</strong><small>Cliente retail</small></td><td><span className={`status status-${order.status.toLowerCase()}`}><span />{labels[order.status]}</span></td><td className="money">${order.total.toLocaleString('es-CO')}</td><td><span className="location"><MapPin size={14} />{order.deliveryAddress}</span></td><td><select aria-label={`Cambiar estado del pedido ${order.id}`} value={order.status} onChange={event => updateStatus(order.id, event.target.value as OrderStatus)}><option value={order.status}>{labels[order.status]}</option>{(Object.keys(labels) as OrderStatus[]).filter(status => status !== order.status && status !== 'CANCELLED').map(status => <option key={status} value={status}>{labels[status]}</option>)}</select></td></tr>)}</tbody></table>{!filteredOrders.length && <div className="empty">No hay pedidos que coincidan con tu búsqueda.</div>}</div>}</div><aside className="route-panel"><div className="route-header"><div><p className="eyebrow">EN TIEMPO REAL</p><h2>Red de entregas</h2></div><span className="live"><i /> LIVE</span></div><div className="map"><div className="map-grid" /><div className="map-road road-a" /><div className="map-road road-b" /><div className="map-road road-c" /><div className="map-pin pin-one"><Truck size={14} /></div><div className="map-pin pin-two"><Truck size={14} /></div><div className="map-pin pin-three"><Truck size={14} /></div><div className="map-label label-one">R-08</div><div className="map-label label-two">R-12</div></div><div className="route-stat"><div><strong>{dashboard.inTransit}</strong><span>vehículos activos</span></div><div><strong>94<span>%</span></strong><span>entregas a tiempo</span></div></div><button className="outline-button">Abrir mapa de operaciones <ArrowUpRight size={15} /></button></aside></section>
    </main>{showForm && <NewOrder onClose={() => setShowForm(false)} onCreated={() => { setShowForm(false); loadData() }} />}</div>
}
function Metric({ icon, label, value, detail, positive, warning }: { icon: React.ReactNode; label: string; value: number; detail: string; positive?: boolean; warning?: boolean }) { return <div className="metric"><div className={`metric-icon ${warning ? 'warning' : ''}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small className={positive ? 'positive' : warning ? 'warning-text' : ''}>{positive && '↗ '}{detail}</small></div></div> }
function NewOrder({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) { const [form, setForm] = useState({ customerName: '', deliveryAddress: '', total: '' }); const [saving, setSaving] = useState(false); async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); await fetch(`${API}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, total: Number(form.total) }) }); onCreated() } return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-heading"><div><p className="eyebrow">NUEVA OPERACIÓN</p><h2>Registrar pedido</h2></div><button type="button" className="close-button" onClick={onClose}><X size={18} /></button></div><label>Nombre del cliente<input required value={form.customerName} onChange={event => setForm({ ...form, customerName: event.target.value })} placeholder="Ej. Laura Gómez" /></label><label>Dirección de entrega<input required value={form.deliveryAddress} onChange={event => setForm({ ...form, deliveryAddress: event.target.value })} placeholder="Calle 00 # 00-00" /></label><label>Total del pedido<input required min="1" type="number" value={form.total} onChange={event => setForm({ ...form, total: event.target.value })} placeholder="0" /></label><button className="primary-button modal-submit" disabled={saving}>{saving ? 'Guardando...' : 'Crear pedido'} <ArrowUpRight size={16} /></button></form></div> }

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
